# Generated by Django 6.0.4 on 2026-04-16 00:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.SlugField(help_text='A short public identifier used in profile and channel URLs.', max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('preferred_language', models.CharField(default='en', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_public_profile', models.BooleanField(default=True)),
                ('allow_live_notifications', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'handle'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('handle'), name='profiles_profile_handle_ci_unique')],
            },
        ),
    ]
