# Generated by Django 6.0.4 on 2026-04-16 00:43

import core.models.fields.janus
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('access_policy', models.CharField(choices=[('open', 'Open'), ('approval_required', 'Approval Required'), ('invite_only', 'Invite Only')], default='approval_required', max_length=32)),
                ('is_waiting_room_enabled', models.BooleanField(default=True)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('passcode_hash', models.CharField(blank=True, max_length=255)),
                ('janus_room_configuration', models.JSONField(blank=True, default=dict)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meeting_rooms', to='profiles.profile')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('participant', 'Participant')], default='participant', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_waiting_room', models.BooleanField(default=False)),
                ('can_manage_participants', models.BooleanField(default=False)),
                ('can_manage_media', models.BooleanField(default=False)),
                ('can_manage_permissions', models.BooleanField(default=False)),
                ('can_manage_chat', models.BooleanField(default=False)),
                ('can_manage_reactions', models.BooleanField(default=False)),
                ('can_manage_recording', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invited_by_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_memberships_granted', to='profiles.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_memberships', to='profiles.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='meetings.meetingroom')),
            ],
            options={
                'ordering': ('room', 'profile'),
            },
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_handle_id', core.models.fields.janus.JanusPluginField(blank=True, db_index=True, identifier='publisher', janus_getter='apps.meetings.services.janus.resolve_janus_session', max_length=255, null=True, plugin_attr='control_handle', plugin_class='janus_api.Plugin', plugin_kwargs_factory='apps.meetings.services.janus.meeting_session_control_plugin_kwargs')),
                ('lifecycle_state', models.CharField(choices=[('scheduled', 'Scheduled'), ('provisioning', 'Provisioning'), ('waiting', 'Waiting'), ('active', 'Active'), ('ending', 'Ending'), ('ended', 'Ended'), ('failed', 'Failed')], default='scheduled', max_length=32)),
                ('janus_room_id', models.CharField(blank=True, max_length=128)),
                ('janus_room_secret', models.CharField(blank=True, max_length=255)),
                ('janus_room_pin', models.CharField(blank=True, max_length=255)),
                ('janus_backend_server', models.CharField(blank=True, max_length=255)),
                ('janus_state', models.JSONField(blank=True, default=dict)),
                ('state_version', models.PositiveBigIntegerField(default=1)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('active_publisher_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.meetingroom')),
                ('started_by_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_meeting_sessions', to='profiles.profile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_display_name', models.CharField(blank=True, max_length=255)),
                ('requested_role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('participant', 'Participant')], default='participant', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('client_state', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_join_requests', to='profiles.profile')),
                ('reviewed_by_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meeting_join_requests', to='profiles.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='meetings.meetingroom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('participant', 'Participant')], default='participant', max_length=32)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('left', 'Left'), ('removed', 'Removed')], default='admitted', max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('can_publish_audio', models.BooleanField(default=True)),
                ('can_publish_video', models.BooleanField(default=True)),
                ('can_share_screen', models.BooleanField(default=False)),
                ('can_chat', models.BooleanField(default=True)),
                ('can_react', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_camera_blocked', models.BooleanField(default=False)),
                ('raised_hand_at', models.DateTimeField(blank=True, null=True)),
                ('janus_publisher_id', models.CharField(blank=True, max_length=128)),
                ('janus_private_id', models.CharField(blank=True, max_length=128)),
                ('janus_state', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_participants', to='meetings.meetingjoinrequest')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participants', to='meetings.meetingroommembership')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='profiles.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meetingroom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='MeetingReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='meetings.meetingsession')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='meetings.participant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('chat', 'Chat'), ('system', 'System'), ('moderation', 'Moderation')], default='chat', max_length=32)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.meetingsession')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='meetings.participant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('room_created', 'Room Created'), ('session_created', 'Session Created'), ('session_provisioned', 'Session Provisioned'), ('session_ended', 'Session Ended'), ('join_request_created', 'Join Request Created'), ('join_request_reviewed', 'Join Request Reviewed'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('participant_removed', 'Participant Removed'), ('participant_updated', 'Participant Updated'), ('chat_message_sent', 'Chat Message Sent'), ('reaction_sent', 'Reaction Sent'), ('janus_handle_attached', 'Janus Handle Attached'), ('janus_handle_failed', 'Janus Handle Failed'), ('state_synced', 'State Synced'), ('cleanup_completed', 'Cleanup Completed')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_events', to='profiles.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetings.meetingsession')),
                ('actor_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='meetings.participant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ParticipantConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socket_id', models.CharField(max_length=255, unique=True)),
                ('transport', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('desktop', 'Desktop App'), ('bot', 'Automation')], default='web', max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('subscribed', 'Subscribed'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('stale', 'Stale')], default='connected', max_length=32)),
                ('client_session_key', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='meetings.participant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_connections', to='profiles.profile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ('-connected_at',),
            },
        ),
        migrations.AddField(
            model_name='meetingjoinrequest',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='meetings.participantconnection'),
        ),
        migrations.CreateModel(
            name='ParticipantMediaHandle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle_type', models.CharField(choices=[('publisher', 'Publisher'), ('subscriber', 'Subscriber'), ('textroom', 'TextRoom')], max_length=32)),
                ('lifecycle_state', models.CharField(choices=[('attaching', 'Attaching'), ('attached', 'Attached'), ('joining', 'Joining'), ('ready', 'Ready'), ('detaching', 'Detaching'), ('detached', 'Detached'), ('failed', 'Failed')], default='attaching', max_length=32)),
                ('janus_session_id', models.CharField(blank=True, max_length=128)),
                ('janus_handle_id', core.models.fields.janus.JanusPluginField(blank=True, callback_factory='core.hooks.janus.plugin_callback_factory', db_index=True, identifier='publisher', identifier_getter='apps.meetings.services.janus.participant_media_handle_identifier', janus_getter='apps.meetings.services.janus.resolve_janus_session', max_length=255, null=True, plugin_attr='handle', plugin_class='janus_api.Plugin', plugin_kwargs_factory='apps.meetings.services.janus.participant_media_plugin_kwargs')),
                ('opaque_id', models.CharField(blank=True, max_length=255)),
                ('jsep_offer', models.JSONField(blank=True, default=dict)),
                ('jsep_answer', models.JSONField(blank=True, default=dict)),
                ('selected_streams', models.JSONField(blank=True, default=list)),
                ('janus_state', models.JSONField(blank=True, default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_handles', to='meetings.participantconnection')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_handles', to='meetings.participant')),
            ],
            options={
                'ordering': ('participant', 'handle_type'),
            },
        ),
        migrations.CreateModel(
            name='ParticipantStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=32)),
                ('media_kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('data', 'Data'), ('screen', 'Screen')], max_length=32)),
                ('janus_mid', models.CharField(max_length=64)),
                ('janus_feed_id', models.CharField(blank=True, max_length=128)),
                ('janus_feed_mid', models.CharField(blank=True, max_length=64)),
                ('codec', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_moderated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('media_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='meetings.participantmediahandle')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='meetings.participant')),
                ('source_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_streams', to='meetings.participant')),
            ],
            options={
                'ordering': ('participant', 'direction', 'media_kind', 'janus_mid'),
            },
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['slug'], name='meeting_room_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['created_by_profile'], name='meeting_room_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['access_policy'], name='meeting_room_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingroommembership',
            index=models.Index(fields=['room', 'role'], name='meeting_room_member_role_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingroommembership',
            index=models.Index(fields=['profile', 'role'], name='meeting_room_profile_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingroommembership',
            constraint=models.UniqueConstraint(fields=('room', 'profile'), name='meeting_room_membership_unique'),
        ),
        migrations.AddIndex(
            model_name='meetingsession',
            index=models.Index(fields=['room', 'lifecycle_state'], name='meeting_session_room_state_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsession',
            index=models.Index(fields=['janus_room_id'], name='meeting_session_janus_room_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsession',
            index=models.Index(fields=['started_by_profile'], name='meeting_session_starter_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['session', 'status'], name='meet_part_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['session', 'role'], name='meet_part_sess_role_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['janus_publisher_id'], name='meet_part_jpub_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('session', 'profile'), name='meeting_participant_unique_per_session_profile'),
        ),
        migrations.AddIndex(
            model_name='meetingreaction',
            index=models.Index(fields=['session', 'created_at'], name='meet_react_sess_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingreaction',
            index=models.Index(fields=['reaction'], name='meeting_reaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingmessage',
            index=models.Index(fields=['session', 'created_at'], name='meet_msg_sess_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingmessage',
            index=models.Index(fields=['kind'], name='meeting_message_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['session', 'created_at'], name='meet_evt_sess_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['event_type', 'created_at'], name='meet_evt_type_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='participantconnection',
            index=models.Index(fields=['session', 'status'], name='meet_conn_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participantconnection',
            index=models.Index(fields=['participant', 'status'], name='meet_conn_part_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participantconnection',
            index=models.Index(fields=['profile', 'status'], name='meet_conn_profile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingjoinrequest',
            index=models.Index(fields=['session', 'status'], name='meet_join_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingjoinrequest',
            index=models.Index(fields=['profile', 'status'], name='meet_join_profile_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('session', 'profile'), name='meeting_pending_join_request_unique_per_session_profile'),
        ),
        migrations.AddIndex(
            model_name='participantmediahandle',
            index=models.Index(fields=['participant', 'handle_type'], name='meet_mh_part_type_idx'),
        ),
        migrations.AddIndex(
            model_name='participantmediahandle',
            index=models.Index(fields=['janus_handle_id'], name='meet_mh_jhandle_idx'),
        ),
        migrations.AddIndex(
            model_name='participantmediahandle',
            index=models.Index(fields=['lifecycle_state'], name='meet_mh_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantmediahandle',
            constraint=models.UniqueConstraint(fields=('participant', 'handle_type'), name='meeting_media_handle_unique_per_type'),
        ),
        migrations.AddIndex(
            model_name='participantstream',
            index=models.Index(fields=['participant', 'direction'], name='meet_stream_part_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='participantstream',
            index=models.Index(fields=['janus_feed_id'], name='meeting_stream_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='participantstream',
            index=models.Index(fields=['is_active', 'is_ready'], name='meet_stream_act_ready_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantstream',
            constraint=models.UniqueConstraint(fields=('media_handle', 'janus_mid'), name='meeting_stream_unique_per_handle_mid'),
        ),
    ]
