# Generated by Django 6.0.4 on 2026-07-10 15:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalMeetingBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("law_firm_workspace", "Law firm workspace"),
                        ],
                        default="law_firm_workspace",
                        max_length=64,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_bindings",
                        to="meetings.meetingroom",
                    ),
                ),
                (
                    "service_owner_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_external_meeting_bindings",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("provider", "external_id"),
                "indexes": [
                    models.Index(
                        fields=["service_owner_profile", "provider"],
                        name="meet_ext_owner_provider_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="meet_ext_provider_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("provider", "room"),
                        name="meet_ext_provider_room_uniq",
                    ),
                ],
            },
        ),
    ]
