# Generated by Django 6.0.4 on 2026-07-12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_externalmeetingbinding"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issuer_name", models.CharField(max_length=255)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True)),
                ("expires_in_seconds", models.PositiveIntegerField()),
                (
                    "initial_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "ready_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_delivery_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("delivery_attempts", models.PositiveIntegerField(default=0)),
                ("last_delivery_error", models.TextField(blank=True)),
                (
                    "issuer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_meeting_invitations",
                        to="profiles.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_invitations",
                        to="meetings.meetingsession",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["ready_email_sent_at", "created_at"],
                        name="meet_invite_ready_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "recipient_email"),
                        name="meet_invite_session_email_uniq",
                    ),
                ],
            },
        ),
    ]
