# Generated by Django 6.0.7 on 2026-07-25 16:25

import core.models.fields.janus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetinginvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsession',
            name='control_handle_id',
            field=core.models.fields.janus.JanusPluginField(blank=True, db_index=True, identifier='publisher', janus_getter='apps.meetings.services.janus.resolve_janus_session', null=True, plugin_attr='control_handle', plugin_class='janus_api.Plugin', plugin_kwargs_factory='apps.meetings.services.janus.meeting_session_control_plugin_kwargs'),
        ),
        migrations.AlterField(
            model_name='meetingsession',
            name='janus_room_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_private_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_publisher_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='janus_handle_id',
            field=core.models.fields.janus.JanusPluginField(blank=True, callback_factory='core.hooks.janus.plugin_callback_factory', db_index=True, identifier='publisher', identifier_getter='apps.meetings.services.janus.participant_media_handle_identifier', janus_getter='apps.meetings.services.janus.resolve_janus_session', null=True, plugin_attr='handle', plugin_class='janus_api.Plugin', plugin_kwargs_factory='apps.meetings.services.janus.participant_media_plugin_kwargs'),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='janus_session_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='opaque_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
