# Generated by Django 6.0.7 on 2026-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meetingsession_control_handle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmediahandle',
            name='opaque_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
