# Generated by Django 6.0.7 on 2026-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetingsession_cleanup_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsession',
            name='janus_room_id',
            field=models.IntegerField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_private_id',
            field=models.IntegerField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_publisher_id',
            field=models.IntegerField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='janus_session_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participantstream',
            name='janus_feed_id',
            field=models.IntegerField(blank=True, max_length=128),
        ),
    ]
