# Generated by Django 6.0.7 on 2026-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meetingsession_janus_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsession',
            name='janus_room_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_private_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_publisher_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='participantstream',
            name='janus_feed_id',
            field=models.IntegerField(blank=True),
        ),
    ]
