# Generated by Django 6.0.7 on 2026-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_meetingsession_control_handle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsession',
            name='janus_room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
