# Generated by Django 6.0.7 on 2026-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_alter_meetingsession_janus_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='janus_private_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_publisher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='janus_session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='opaque_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participantstream',
            name='codec',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='participantstream',
            name='janus_feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantstream',
            name='janus_feed_mid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
