# Generated by Django 6.0.7 on 2026-08-20

import uuid

import django.db.models.deletion
from django.db import migrations, models


def clear_non_positive_janus_ids(apps, schema_editor):
    """Normalize legacy sentinel IDs before adding unsigned bigint checks."""

    model_fields = {
        "MeetingSession": ("control_handle_id", "janus_room_id"),
        "Participant": ("janus_publisher_id", "janus_private_id"),
        "ParticipantMediaHandle": ("janus_session_id", "janus_handle_id"),
        "ParticipantStream": ("janus_feed_id",),
    }
    quote_name = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        for model_name, field_names in model_fields.items():
            model = apps.get_model("meetings", model_name)
            table_name = quote_name(model._meta.db_table)
            for field_name in field_names:
                column_name = quote_name(model._meta.get_field(field_name).column)
                cursor.execute(
                    f"UPDATE {table_name} SET {column_name} = NULL "
                    f"WHERE {column_name} <= %s",
                    [0],
                )


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0011_alter_participant_janus_private_id_and_more"),
    ]

    operations = [
        migrations.RunPython(
            clear_non_positive_janus_ids,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="JrtcEventReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(editable=False, unique=True)),
                ("event_type", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_attempts", models.PositiveIntegerField(default=1)),
                ("duplicate_count", models.PositiveBigIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("received_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "received_at"],
                        name="meet_jrtc_receipt_status_idx",
                    ),
                    models.Index(
                        fields=["event_type", "received_at"],
                        name="meet_jrtc_receipt_type_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JrtcBrowserEventOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dispatch_index", models.PositiveIntegerField()),
                ("socket_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivery_attempts", models.PositiveIntegerField(default=0)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browser_outbox",
                        to="meetings.jrtceventreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "dispatch_index"),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="meet_jrtc_outbox_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt", "dispatch_index", "socket_id"),
                        name="meet_jrtc_outbox_target_uniq",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="meetingsession",
            name="control_handle_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meetingsession",
            name="janus_room_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="janus_private_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="janus_publisher_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participantmediahandle",
            name="janus_handle_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participantmediahandle",
            name="janus_session_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantmediahandle",
            name="runtime_owner_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="participantmediahandle",
            name="runtime_claim_id",
            field=models.UUIDField(
                blank=True,
                default=None,
                editable=False,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participantstream",
            name="janus_feed_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="participantmediahandle",
            index=models.Index(
                fields=["janus_session_id", "janus_handle_id"],
                name="meet_mh_jsess_jhandle_idx",
            ),
        ),
    ]
