# Generated by Django 6.0.9 on 2026-10-08 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_jrtc_persistence_and_event_receipts'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrtcbrowsereventoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('discarded', 'Discarded')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='meetingsession',
            name='control_handle_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meetingsession',
            name='janus_room_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_private_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='janus_publisher_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='janus_handle_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='participantmediahandle',
            name='janus_session_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='participantstream',
            name='janus_feed_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='jrtcbrowsereventoutbox',
            index=models.Index(fields=['status', 'updated_at'], name='meet_jrtc_outbox_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingsession',
            constraint=models.CheckConstraint(condition=models.Q(('control_handle_id__isnull', True), ('control_handle_id__gt', 0), _connector='OR'), name='meet_sess_control_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='meetingsession',
            constraint=models.CheckConstraint(condition=models.Q(('janus_room_id__isnull', True), ('janus_room_id__gt', 0), _connector='OR'), name='meet_sess_room_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('janus_publisher_id__isnull', True), ('janus_publisher_id__gt', 0), _connector='OR'), name='meet_part_pub_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('janus_private_id__isnull', True), ('janus_private_id__gt', 0), _connector='OR'), name='meet_part_private_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='participantmediahandle',
            constraint=models.CheckConstraint(condition=models.Q(('janus_session_id__isnull', True), ('janus_session_id__gt', 0), _connector='OR'), name='meet_mh_session_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='participantmediahandle',
            constraint=models.CheckConstraint(condition=models.Q(('janus_handle_id__isnull', True), ('janus_handle_id__gt', 0), _connector='OR'), name='meet_mh_handle_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='participantstream',
            constraint=models.CheckConstraint(condition=models.Q(('janus_feed_id__isnull', True), ('janus_feed_id__gt', 0), _connector='OR'), name='meet_stream_feed_gt_zero'),
        ),
    ]
