web: DJANGO_SETTINGS_MODULE=conf.settings uv run python -m uvicorn conf.asgi:application --host 0.0.0.0 --port ${PORT:-8000}
worker: DJANGO_SETTINGS_MODULE=conf.settings uv run python -m celery -A conf worker -P solo -l INFO -E
beat: DJANGO_SETTINGS_MODULE=conf.settings uv run python -m celery -A conf.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
